<h2> Przegląd danych </h2>
Zapoznanie się z danymi z tabel

In [4]:
import pandas as pd

all_players_check = 'Dane/all_players-checkpoint.csv'
df_all_players_check = pd.read_csv(all_players_check)
display(df_all_players_check.head())
df_all_players_check.info()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,Gls,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerialDuels_Won,AerialDuels_Lost,Cmp
0,Teresa Abilleira,es ESP,MF,Real Madrid,22-333,2000.0,9,7,648,3,...,0.0,18.0,15.0,0.0,0.0,0,52.0,4.0,5.0,0.0
1,Jessica Aby,ci CIV,"FW,MF",Alavés,24-175,1998.0,10,4,383,1,...,2.0,3.0,7.0,0.0,0.0,0,21.0,6.0,11.0,0.0
2,Charity Adule,NaN,FW,Alhama,29-031,1993.0,1,0,14,0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,2.0,0.0
3,Júlia Aguado,NaN,"FW,MF",Levante,22-220,2000.0,5,0,50,3,...,2.0,0.0,0.0,0.0,0.0,0,2.0,1.0,0.0,0.0
4,Yolanda Aguirre,es ESP,GK,Sevilla,24-046,1998.0,4,4,360,0,...,0.0,0.0,0.0,0.0,0.0,1,2.0,1.0,1.0,0.0

<class 'pandas.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Columns: 111 entries, Player to Cmp
dtypes: float64(90), int64(14), str(7)
memory usage: 1.1 MB

In [2]:
all_players = 'Dane/all_players.csv'
df_all_players = pd.read_csv(all_players)
display(df_all_players.head())

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,Gls,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerialDuels_Won,AerialDuels_Lost,Cmp
0,Teresa Abilleira,es ESP,MF,Real Madrid,22-333,2000.0,9,7,648,3,...,0.0,18.0,15.0,0.0,0.0,0,52.0,4.0,5.0,0.0
1,Jessica Aby,ci CIV,"FW,MF",Alavés,24-175,1998.0,10,4,383,1,...,2.0,3.0,7.0,0.0,0.0,0,21.0,6.0,11.0,0.0
2,Charity Adule,NaN,FW,Alhama,29-031,1993.0,1,0,14,0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,2.0,0.0
3,Júlia Aguado,NaN,"FW,MF",Levante,22-220,2000.0,5,0,50,3,...,2.0,0.0,0.0,0.0,0.0,0,2.0,1.0,0.0,0.0
4,Yolanda Aguirre,es ESP,GK,Sevilla,24-046,1998.0,4,4,360,0,...,0.0,0.0,0.0,0.0,0.0,1,2.0,1.0,1.0,0.0